export type Media={id:string;url:string;altText:string;width?:number;height?:number;provider?:string|null;providerAssetId?:string|null;attributionName?:string|null;attributionUrl?:string|null;license?:string|null;visualOrigin?:string|null;caption?:string|null}
export type Category={id:string;name:string;slug:string;description:string;color:string;sortOrder:number}
export type Post={id:string;type:'POST'|'PAGE';status:string;title:string;slug:string;excerpt:string;category:string;categoryId?:string|null;categoryRef?:Category|null;authorName:string;sourceLabel?:string|null;sourceUrl?:string|null;isFeatured:boolean;markdown:string;html:string;wordCount:number;tags:string[];seoTitle?:string|null;seoDescription?:string|null;publishedAt?:string|null;scheduledAt?:string|null;createdAt:string;updatedAt:string;coverMedia?:Media|null;imageCredits?:Media[];language?:'zh-CN'|'en';availableLanguages?:Array<'zh-CN'|'en'>;visualNeedsReview?:boolean}
export type Envelope<T>={data:T;meta?:{page:number;limit:number;total:number;pages:number}}
type Query={limit?:number;page?:number;category?:string;categoryId?:string;featured?:boolean;search?:string;tag?:string;lang?:'zh-CN'|'en'}
const clean=(value?:string)=>value?.trim()
export function queryString(q:Query){const params=new URLSearchParams();if(q.limit)params.set('limit',String(q.limit));if(q.page)params.set('page',String(q.page));if(clean(q.category))params.set('category',q.category!);if(clean(q.categoryId))params.set('categoryId',q.categoryId!);if(typeof q.featured==='boolean')params.set('featured',String(q.featured));if(clean(q.search))params.set('search',q.search!);if(clean(q.tag))params.set('tag',q.tag!);if(q.lang==='en')params.set('lang','en');return params.toString()}
export async function fetchPosts(q:Query={}){const qs=queryString(q);const res=await fetch(`/api/v1/posts${qs?`?${qs}`:''}`);const value=await res.json();if(!res.ok)throw new Error(value.error?.message??'Could not load posts');return value as Envelope<Post[]>}
export async function fetchPageBySlug(slug:string){const res=await fetch(`/api/v1/pages/${slug}`);const value=await res.json();if(!res.ok)throw new Error(value.error?.message??'Could not load page');return value.data as Post}
export async function fetchPostBySlug(slug:string,lang:'zh-CN'|'en'='zh-CN'){const res=await fetch(`/api/v1/posts/${slug}${lang==='en'?'?lang=en':''}`);const value=await res.json();if(!res.ok)throw new Error(value.error?.message??'Article not found');return value.data as Post}
export async function fetchCategories(){const res=await fetch('/api/v1/categories');const value=await res.json();if(!res.ok)throw new Error(value.error?.message??'Could not load categories');return value as Envelope<Category[]>}
